README.md, wallets.json
1. We add `url_scheme` field for the wallet app so it can be opened without going through the browser.
2. Restructure bridge info as a list of "bridge options" that can be extended in the future with websockets, variants of the protocol etc.
=> Bridge layout for future extensibility

wallets.json
- [] JS bridge as a browser extention for [Google Chrome](<chrome store url>), ..., browsers.
Ton Connect 2.0 is supported on TonSafe versions >= 2.2
[a demo dapp with integrated wallet](https://raw.githubusercontent.com/tonsafe/wallets-list/main/Tonsafe-Tonconnect-Demo.m4v)
* [telegram] [https://t.me/tonsafesupportbot]
* [email] ops@tonsafe.org
=> TonSafe now supports Ton Connect 2.0 protocol.

wallets-v2.json
The decision was made due to the inactivity of Tonflow, their website https://tonflow.net is no longer operational, and there appears to be no ongoing support or maintenance for the wallet. 
This removal is to ensure that the users have access to reliable and actively supported wallets.
=> Remove Tonflow from the list of supported wallets

wallets-v2.json
Recent activity trends indicate a shift in usage patterns, with MyTonWallet showing relatively higher user engagement compared to OpenMask.
To reflect these trends and provide the users with the most relevant and actively used wallets first, this PR repositions MyTonWallet ahead of OpenMask in the list.
=> Reorder wallets based on activity

wallets-v2.json
https://t.me/desimtonbot/start
[@wpwwDEV](https://t.me/wpwwDEV)
@sijuz
=> Update DeWallet image

wallets-v2.json
* telegram
* email
* discord
* ...
=> fix: correct universal link for delab wallet

wallets-v2.json
Add SafePal wallet info
* telegram
* email
* discord
* ...
=> Add SafePal Wallet

wallets-v2.json
* telegram
* email
* discord
* ...
=> Change OKX Wallet universal link to okx.com

wallets-v2.json
The wallet has been temporarily removed due to issues with the logo link.
=> feat: temporary remove bybit wallet

wallets-v2.json
MetaMask is currently flagging TON Space's bridge domain as suspicious, affecting all desktop TON dApps users who have the MetaMask extension installed. 
This PR temporarily changes the bridge url to an alternative domain while we work with MetaMask team to whitelist the original domain. This change ensures uninterrupted functionality for desktop users.
=> Switch TON Space to alternative bridge url temporarily

wallets-v2.json
This PR updates the order of wallets in the `wallets-list.json` based on the latest analytics data from December 9, 2024 of wallet usage and adoption rates. The new order reflects actual market penetration and user preferences, which should provide a better user experience by presenting the most commonly used wallets first.
The updated order prioritizes wallets with higher user engagement while maintaining support for all existing integrations. This change is purely presentational and does not affect any functional aspects of TON Connect.
=> feat: reorganize wallets list for 09-12-2024

wallets-v2.json
=> feat: add Bitget Wallet Lite

wallets-v2.json
https://demo-dapp-with-wallet-ten.vercel.app/
telegram: @stanta 
telegram: @egorkqq 
email: st@architecton.tech
email: egor@architecton.tech
=> Add Architec.ton wallet

wallets-v2.json
This PR adds supported features information to the wallets-list manifests.
Previously, wallets only reported their supported features during connection. Now this information is included directly in the wallets-list, allowing dApps to filter compatible wallets before connection based on required features.
=> feat: add supported features to wallet manifests

wallets-v2.json
@wallet team has informed that they've added support for extra currency. This pr updates their manifest to reflect this new capability, allowing dApps to utilize this feature.
=> feat: add extra currency support for telegram wallet

wallets-v2.json
This PR updates the feature specifications for ecosystem wallets:
- Wallet in Telegram: Increased max messages limit from 4 to 255
- MyTonWallet: Increased max messages limit from 4 to 255  
- Tonhub: Increased max messages limit from 4 to 255 and enabled extra currency supported
=> feat: update wallet features for Wallet in Telegram, MyTonWallet and Tonhub

README.md
Add features field documentation to wallet entry format for specifying TON Connect capabilities
=> docs: add features field specification to wallet entry format

wallets-v2.json
=> Add Nicegram Wallet

wallets-v2.json
Temporarily removing Tobi wallet from the supported wallets list due to non-functional bridge and lack of response from the team. The wallet will be re-added once the technical issues are resolved and communication is restored.
=> feat: remove Tobi wallet temporarily due to bridge issues

wallets-v2.json
* telegram
* email
* discord
* ...
=> add Cactus Link wallet

wallets-v2.json
Added `windows` and `linux` in platform list for tonkeeper
=> Added `windows` and `linux` in platform list of wallets-v2 for tonkeeper
