ton-blockchain/wallets-list

- wallets.json
This reverts commit ff542d5ac9390320c2540da5adcc0a8f42cd0e60, reversing changes made to 06010d9bc3005e45e0c6e40b15eedd29718beadb.
> Revert "Merge pull request #2 from KuznetsovNikita/feature/openMask"

- wallets.json
* telegram: https://t.me/unexpectedusername
* email: mytonwallet@gmail.com
> Add MyTonWallet

- wallets.json
* telegram @dvlkv
* email danila@whalescorp.com
> Add tonhub

- wallets.json
Reverts ton-blockchain/wallets-list#14
> Revert "Add tonhub": issues with universal_url

- wallets.json
* telegram
* email
* discord
* ...
> chore: add tonhub with universal_url

- wallets.json
[a demo dapp with integrated wallet](https://tonflow.net/assets/videos/tonflow_ton_connect_demo_app_walkthrough.mp4)
* telegram -> @tonflow_support_bot
* email -> itonflow@gmail.com
> TonFlow now support TonConnect 2.0

- wallets.json
- https://static.obbana.ru/demo-dapp-with-react-ui/index.html
- Unfortunately, the `sendTransaction` button performs unnecessary redirection (not our problem), otherwise it works
- Windows https://disk.yandex.ru/d/-ARMLrGXT2dFmA
- Linux https://disk.yandex.ru/d/1Rp9lPxNwGw-dA
- MacOS (on demand)
* telegram
* https://t.me/troman29
* https://t.me/unexpectedusername
> Add SSE bridge to MyTonWallet

- wallets-v2.json
Added tonkepeer custom deeplink in order to provide more smooth redirection UI on desktop
> Tonkepeer config update

- wallets-v2.json
> Update MyTonWallet platforms

- wallets-v2.json
> telegram-wallet config update

- wallets-v2.json
> add bitget ton wallet to list

- wallets-v2.json
https://t.me/desimtonbot/start
[@wpwwDEV](https://t.me/wpwwDEV)
@sijuz
> Change DeWallet image

- wallets-v2.json
https://t.me/desimtonbot/start
[@wpwwDEV](https://t.me/wpwwDEV)
@sijuz
>  Update DeWallet SSE Bridge

- wallets-v2.json
> Added OKX and OKXTR Web3 Wallet

- wallets-v2.json
> Update OKX universal links

- wallets-v2.json
https://hot-example-connect.surge.sh/
> feat: add hot wallet

- wallets-v2.json
> feat(hot-wallet): change icon

- wallets-v2.json
Hi team,
This PR adjusts the SSE bridge of the `Bitget Wallet` to use our own bridge. Our bridge has been built based on your bridge2 SDK and has been thoroughly tested. Please review and merge this PR. If you have any concerns, please feel free to reach out to us.
Bitget Wallet team
> feat(bgw): Adjust the sse bridge of Bitget Wallet

- wallets-v2.json
* email: xianghongxiang@gmail.com
> feat: add bybit ton wallet to the list

- wallets-v2.json
> feat(bybit): support chrome

- wallets-v2.json
[a demo dapp with integrated wallet](https://weixuefeng.github.io/demo-dapp-with-wallet/)
> feat: update gatewallet

- wallets-v2.json
- [demo-dapp-with-react-ui](https://ton-connect.github.io/demo-dapp-with-react-ui/)
- [use nora wallet](https://lucifer.ren/demo-dapp-with-react-ui/) use nora wallet
> add binance web3 wallet

- wallets-v2.json
* telegram
* email
* discord
* ...
> fix: change binance web3 wallet image host

- wallets-v2.json
[a demo dapp with integrated wallet](https://front.staging.fintopio.com/)
*  [@shybetska_mariia](https://t.me/shybetska_mariia)
> Add Fintopio wallet

- wallets-v2.json
> Update Fintopio wallet name

- wallets-v2.json
* telegram
* email
* discord
* ...
> Add okx mini wallet and unload tr

- wallets-v2.json
[Test Demo](https://demo-dapp-with-wallet-eight.vercel.app/)
> feat: add Bybit wallet integration with replacing bybit logo url

- wallets-v2.json
This PR updates the order of wallets in the `wallets-list.json` based on recent analytics data of wallet usage and adoption rates. The new order reflects actual market penetration and user preferences, which should provide a better user experience by presenting the most commonly used wallets first.
The updated order prioritizes wallets with higher user engagement while maintaining support for all existing integrations. This change is purely presentational and does not affect any functional aspects of TON Connect.
**Please review and approve if the new ordering looks correct to you.**
> feat: reorganize wallets list based on usage analytics

- wallets-v2.json
* telegram
* email
* discord
* ...
> bitget web3

- wallets-v2.json
* telegram: https://t.me/DungLQ94
* email: dung@tobilabs.io
* discord
* ...
> feat: add Tobi wallet

- wallets-v2.json
Hi team,
This PR is for updating the Bitget Wallet logo. Please help to review and merge it.
Bitget Wallet team
> feat: update bitget wallet logo

- wallets-v2.json
> Add Tomo Wallet

- .github/workflows/comment.md
- .github/workflows/pr-comment.yml
This PR introduces an automated workflow that adds informative comments to new pull requests, which provides clear guidance on the TON Connect integration and audit process.
> chore: add automated pr comment workflow

- wallets-v2.json
> Add deeplink of MyTonWallet

- wallets-v2.json
Hi TON team,
In addition to [Mirai App](https://github.com/ton-blockchain/wallets-list/pull/116) on mobile platforms we currently support, we have the Mirai App on Telegram in order to maximize our user experience. TON and TON Connect have been supported in this app. We kindly request your review. If you have any questions or concerns, please don't hesitate to reach out to us.
Best regards,
Kayy (Tien Tran) from the Mirai App team.
[a demo dapp with integrated wallet](https://miraiapp-ton-demo.web.app/)
**Note:** In wallet list, please select Mirai Telegram App
* email: tientran@mirailabs.co
> feat: add Mirai Telegram App

- wallets-v2.json
[a demo dapp with integrated wallet](https://test-tp.tokenpocket.pro/ton/index.html)
* [chendatony31](https://t.me/chendatony31)
> Add TokenPocket Wallet

- wallets-v2.json
[a demo dapp with integrated wallet](https://github.com/uxuySafe/examples/tree/main/examples/tonconnect-v2/src/pages)
> feat(uxuy): add UXUY Wallet

- wallets-v2.json
- [] JS bridge as a browser extention for [Google Chrome](<chrome store url>), ..., browsers.
- [x ] HTTP bridge as a desctop wallet app for [Windows](<link>), [macOS](<link>), ... .
[Demo dapp with integrated wallet](https://tonkeeper.github.io/demo-dapp-with-tk-pro/)
* telegram https://t.me/siandreev
> Tonkeeper Pro mobile

- wallets-v2.json
[a demo dapp with integrated wallet](http://45.9.149.136:5173/)
* telegram https://t.me/free_chibakova
> Add BLITZ wallet

- wallets-v2.json
* telegram
* email
* discord
* ...
> Update kolo bridge URL

- wallets-v2.json
[a demo dapp with integrated wallet](https://demo-dapp-with-wallet-black.vercel.app/)
* telegram
* email
* discord
> feat: add imToken wallet
